$date = Get-Date -Format "yyyy-MM-dd"
$sitemap = @"
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <url>
        <loc>https://ugeducation.center/</loc>
        <lastmod>$date</lastmod>
        <priority>1.0</priority>
    </url>
    <url>
        <loc>https://ugeducation.center/cbse-school-in-akbarpur/</loc>
        <lastmod>$date</lastmod>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://ugeducation.center/best-school-in-kanpur-dehat/</loc>
        <lastmod>$date</lastmod>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://ugeducation.center/admissions/</loc>
        <lastmod>$date</lastmod>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://ugeducation.center/about-school/</loc>
        <lastmod>$date</lastmod>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://ugeducation.center/facilities/</loc>
        <lastmod>$date</lastmod>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://ugeducation.center/contact/</loc>
        <lastmod>$date</lastmod>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://ugeducation.center/blog/</loc>
        <lastmod>$date</lastmod>
        <priority>0.7</priority>
    </url>
    <url>
        <loc>https://ugeducation.center/blog/best-cbse-schools-in-akbarpur/</loc>
        <lastmod>$date</lastmod>
        <priority>0.6</priority>
    </url>
    <url>
        <loc>https://ugeducation.center/blog/why-choose-cbse-board/</loc>
        <lastmod>$date</lastmod>
        <priority>0.6</priority>
    </url>
    <url>
        <loc>https://ugeducation.center/blog/top-schools-in-kanpur-dehat/</loc>
        <lastmod>$date</lastmod>
        <priority>0.6</priority>
    </url>
    <url>
        <loc>https://ugeducation.center/blog/how-to-choose-school-for-child/</loc>
        <lastmod>$date</lastmod>
        <priority>0.6</priority>
    </url>
    <url>
        <loc>https://ugeducation.center/blog/importance-of-extracurriculars/</loc>
        <lastmod>$date</lastmod>
        <priority>0.6</priority>
    </url>
    <url>
        <loc>https://ugeducation.center/blog/future-ready-education/</loc>
        <lastmod>$date</lastmod>
        <priority>0.6</priority>
    </url>
    <url>
        <loc>https://ugeducation.center/blog/understanding-holistic-development/</loc>
        <lastmod>$date</lastmod>
        <priority>0.6</priority>
    </url>
    <url>
        <loc>https://ugeducation.center/blog/role-of-technology-in-education/</loc>
        <lastmod>$date</lastmod>
        <priority>0.6</priority>
    </url>
    <url>
        <loc>https://ugeducation.center/blog/parent-teacher-synergy/</loc>
        <lastmod>$date</lastmod>
        <priority>0.6</priority>
    </url>
    <url>
        <loc>https://ugeducation.center/blog/building-confidence-in-kids/</loc>
        <lastmod>$date</lastmod>
        <priority>0.6</priority>
    </url>
</urlset>
"@
Set-Content -Path "c:\Users\AVN\Downloads\uged\sitemap.xml" -Value $sitemap -Encoding UTF8
Write-Output "sitemap.xml created successfully."
